version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

  server1:
    build: ./server
    container_name: server1
    environment:
      - PORT=8001
      - SERVER_NAME=Server-1
    depends_on:
      - redis

  server2:
    build: ./server
    container_name: server2
    environment:
      - PORT=8002
      - SERVER_NAME=Server-2
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8085:8080"
    depends_on:
      - server1
      - server2
